---
- name: Ensure that these packages are at their latest version
  hosts: localhost
  remote_user: root
  gather_facts: yes
  tasks:
    - name: install these packages
      yum:
#            update_cache: yes
    - name: install these packages
      package:
        name: "{{ item }}"
        state: latest
      with_items:   
         - httpd
         - bind
         - ftp
         - mysql
         - vsftpd
    - name: ensure that these service have been started and enabled automatically
      service:
       name: "{{ item }}"
       state: started
       enabled: yes
      with_items:
          - httpd
          - vsftpd
          - named
#          - ftp
    - name: make sure firewall allows these services
      firewalld:
       service: "{{ item }}"
       permanent: yes
       immediate: yes
       state: enabled
      with_items:
          - http
#          - named
#          - vsftpd
#          - ftp
    - name: create these directories
      file:
       path: "{{ item }}"
       state: directory 
       recurse: yes
      with_items:    
          -  /home/kwabena/fanta
          -  /home/mexia27/hate
          - /var/www/lower
    - name: create these folders
      file:
       path: "{{ item }}"
       state: absent
      with_items:
          - /home/kwabena/fanta
          - /home/mexia27/hate
          - /var/www/lower
      tags: DONT
#       recurse: yes
          #       owner: root
#       group: root
#       mode: 0755
